version: "3.7"

# Services to run
services:
  express-api: # name of backend service
    container_name: backend-api
    env_file:
      - .env.production.local
    enviroment:
      - PORT=${PORT}
      - API_VERSION=${API_VERSION}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOG_DIR=${LOG_DIR}
      - EXTERNAL_API=${EXTERNAL_API}
      - ORIGIN=${ORIGIN}
    ports:
      - 3000:3000
    restart: always
